stages:
- name: build and push docker image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest
      pushRemote: true
      registry: harbor71.iiidevops.org
    env:
      PLUGIN_BUILD_ARGS: --progress=tty --network=host
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: https://harbor71.iiidevops.org
      PLUGIN_MTU: "1000"
    when:
      branch:
        include:
        - master
        - develop

# (選擇性) 原始碼資安掃描(必須有安裝設定 Checkmarx)
- name: Scan source code
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-source-scan
      version: 0.1.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-scan
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
        harbor.host: "harbor71.iiidevops.org"
        # 基礎pipeline參數
        git.url: ${CICD_GIT_URL}
        git.repoName: ${CICD_GIT_REPO_NAME}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
        # web參數設定
        checkmarx.enabled: true
        checkmarx.runnerVersion: "1.0.0"
        sonarqube.enabled: true
        sonarqube.runnerVersion: latest
  when:
    branch:
      include:
        - master
        - checkmarx

# (選擇性)部屬使用者的資料庫
- name: Deploy db
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-db
      version: 0.1.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
      #targetNamespace: p-v2nzs-pipeline
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        # 這裡是為了50與140環境測試
        git.host: "gitlab71.iiidevops.org"
        # 這裡是為了告訴要處理的git來源為何
        git.repoName: ${CICD_GIT_REPO_NAME}
        git.branch: ${CICD_GIT_BRANCH}
        db.type: postgresql
        db.gui: true
        # 使用者資料庫管理密碼
        db.username: bear
        db.password: IIIdevops123!
        # 使用者初始想要建立的資料庫名稱
        db.name: tododb
    timeout: 60
    when:
      branch:
        include:
          - master

# 部屬使用者應用(app)
- name: Deploy app-web
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-dev-charts3-web
      version: 0.3.0
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-serv
      targetNamespace: ${CICD_GIT_REPO_NAME}
      answers:
        pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
        harbor.host: harbor71.iiidevops.org
        git.url: ${CICD_GIT_URL}
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: ${CICD_GIT_REPO_NAME}
        web.type: spring
        web.imageTag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest
        web.debug: true
        newman.enabled: true
        newman.runnerVersion: 1.0.0
        webinspect.enabled: true
        webinspect.runnerVersion: 1.0.0
        webinspect.startPath: /todos/list/
    when:
      branch:
        include:
          - master
          - develop
